# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sathwik GS
tagline:          'A Jekyll theme'
description:      'Computer Hardware Engineer'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

email: sathwikgs97@gmail.com
github_username: sathwikgs